version: '3.8'
services: 
  redis:
    env_file:
      - .env.local
    image: redis:latest
    command: ["redis-server", "--requirepass", "${CACHE_PASSWORD}"]
    restart: always
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    networks:
      - mp-network
  db: 
    env_file:
      - .env.local
    image: mysql:latest
    restart: always 
    command: --init-file /docker-entrypoint-initdb.d/init.sh
    environment: 
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports: 
      - '${DATABASE_PORT}:${DATABASE_PORT}' 
    networks:
      - mp-network
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
volumes:
  app-log:
    external: true
networks:
  mp-network:
    external: true
