name: Node.js CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Prettier Format
        run: yarn format
      - name: Eslint Format and Check
        run: yarn lint
      - name: Unit Testing
        run: yarn test